### ISSUE TITLE
Practica9-Contrato compilado

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-9-contrato-compilado-equipo-irving#3]
[Practica 9-Contrato compilado-Equipo Irving.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-contrato-compilado-equipo-irving/files/11551129/Practica.9-Contrato.compilado-Equipo.Irving.pdf)

**Comment by Heidi-19** [comment]
Calificación = 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
